//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanDigitization_api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlanDigitizationEntities : DbContext
    {
        public PlanDigitizationEntities()
            : base("name=PlanDigitizationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlarmTable_Setting> AlarmTable_Setting { get; set; }
        public virtual DbSet<Daywise> Daywises { get; set; }
        public virtual DbSet<DayWise_Availability> DayWise_Availability { get; set; }
        public virtual DbSet<DowntimeDetail> DowntimeDetails { get; set; }
        public virtual DbSet<DowntimeSetting> DowntimeSettings { get; set; }
        public virtual DbSet<Live> Lives { get; set; }
        public virtual DbSet<Live_Availability> Live_Availability { get; set; }
        public virtual DbSet<LossesTable_Setting> LossesTable_Setting { get; set; }
        public virtual DbSet<MachineAlarm> MachineAlarms { get; set; }
        public virtual DbSet<MachineLoss> MachineLosses { get; set; }
        public virtual DbSet<RawAvailability> RawAvailabilities { get; set; }
        public virtual DbSet<RAWTable> RAWTables { get; set; }
        public virtual DbSet<ShiftSetting> ShiftSettings { get; set; }
        public virtual DbSet<Shiftwise> Shiftwises { get; set; }
        public virtual DbSet<ShiftWise_Availability> ShiftWise_Availability { get; set; }
        public virtual DbSet<tbl_Live_Operator_Efficiency> tbl_Live_Operator_Efficiency { get; set; }
        public virtual DbSet<tbl_MasterProduct> tbl_MasterProduct { get; set; }
        public virtual DbSet<tbl_Raw_Operator_Efficiency> tbl_Raw_Operator_Efficiency { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<tbl_toolcount> tbl_toolcount { get; set; }
        public virtual DbSet<tbl_toollist> tbl_toollist { get; set; }
        public virtual DbSet<tbl_tooloperating_distance> tbl_tooloperating_distance { get; set; }
        public virtual DbSet<tbl_tooloperating_hrs> tbl_tooloperating_hrs { get; set; }
    }
}
