//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanDigitization_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daywise
    {
        public int ID { get; set; }
        public string Linecode { get; set; }
        public string Day { get; set; }
        public string Variantcode { get; set; }
        public Nullable<int> TotalOkParts { get; set; }
        public Nullable<int> TotalNokParts { get; set; }
        public Nullable<int> TotalReworkParts { get; set; }
        public Nullable<decimal> Firstpassyeild { get; set; }
        public Nullable<decimal> Quality { get; set; }
        public Nullable<decimal> COPQ { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
