//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanDigitization_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DowntimeSetting
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Shift_ID { get; set; }
        public Nullable<System.TimeSpan> DownTime_start { get; set; }
        public Nullable<System.TimeSpan> DownTime_End { get; set; }
        public Nullable<int> DurationTime { get; set; }
        public string Description { get; set; }
    }
}
