//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanDigitization_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineLoss
    {
        public int ID { get; set; }
        public string Line_Code { get; set; }
        public string Machine_Code { get; set; }
        public string Shift_ID { get; set; }
        public Nullable<int> Loss_ID { get; set; }
        public Nullable<System.DateTime> Start_Time { get; set; }
        public Nullable<System.DateTime> End_Time { get; set; }
        public Nullable<System.DateTime> Time_Stamp { get; set; }
    }
}
