//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanDigitization_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawAvailability
    {
        public int ID { get; set; }
        public string Shift_Id { get; set; }
        public string Line_Code { get; set; }
        public string Machine_Code { get; set; }
        public string Variant_Code { get; set; }
        public Nullable<int> Machine_Status { get; set; }
        public Nullable<int> Automodeselected { get; set; }
        public Nullable<int> Manualmodeselected { get; set; }
        public Nullable<int> Automoderunning { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
