//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanDigitization_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAWTable
    {
        public int ID { get; set; }
        public string Shift_Id { get; set; }
        public string Line_Code { get; set; }
        public string Machine_Code { get; set; }
        public string Variant_Code { get; set; }
        public string Machine_Status { get; set; }
        public Nullable<int> OK_Parts { get; set; }
        public Nullable<int> NOK_Parts { get; set; }
        public Nullable<int> Rework_Parts { get; set; }
        public string Rejection_Reasons { get; set; }
        public Nullable<System.DateTime> Time_Stamp { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Auto__Mode_Selected { get; set; }
        public Nullable<int> Manual_Mode_Slected { get; set; }
        public Nullable<int> Auto_Mode_Running { get; set; }
    }
}
