//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanDigitization_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Live_Operator_Efficiency
    {
        public int Id { get; set; }
        public string Line_code { get; set; }
        public string Operation { get; set; }
        public string OperatorName { get; set; }
        public string Variant_Code { get; set; }
        public Nullable<decimal> Expected_Cycle_Time { get; set; }
        public Nullable<decimal> Latest_Cycle_Time { get; set; }
        public Nullable<int> Target_Production { get; set; }
        public Nullable<int> Total_OKParts { get; set; }
        public Nullable<int> Total_NOKParts { get; set; }
    }
}
