//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanDigitization_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Raw_Operator_Efficiency
    {
        public int Id { get; set; }
        public string Line_Code { get; set; }
        public string Machine_Code { get; set; }
        public string Shift_Id { get; set; }
        public string Variant_Code { get; set; }
        public Nullable<int> Machine_Status { get; set; }
        public string OperatorID { get; set; }
        public Nullable<int> Manual_CycleTime { get; set; }
        public Nullable<System.DateTime> StartTime_Operation { get; set; }
        public Nullable<System.DateTime> EndTime_Operation { get; set; }
        public Nullable<System.DateTime> Time_Stamp { get; set; }
        public Nullable<int> Ok_Parts { get; set; }
        public Nullable<int> NOk_Parts { get; set; }
    }
}
