//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanDigitization_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MasterProduct
    {
        public int MP_ID { get; set; }
        public string ProductName { get; set; }
        public string ProductID { get; set; }
        public string ProductDescription { get; set; }
        public string OperationName { get; set; }
        public string MachineName { get; set; }
        public string RecipeName { get; set; }
        public Nullable<decimal> CycleTime { get; set; }
    }
}
